SELECT p1.ID
FROM ECOLI_DATA AS p1
JOIN (SELECT o1.ID, o2.PARENT_ID FROM ECOLI_DATA AS o1 JOIN ECOLI_DATA AS o2 ON o1.PARENT_ID = o2.ID) AS p2 
ON p1.PARENT_ID = p2.ID
WHERE p2.PARENT_ID IS NULL
ORDER BY ID;
