SELECT A0.ID, A1.FISH_NAME, A1.LENGTH
FROM (SELECT F.ID AS ID, N.FISH_NAME AS FISH_NAME, F.LENGTH AS LENGTH
      FROM FISH_INFO AS F
      JOIN FISH_NAME_INFO AS N
      ON N.FISH_TYPE = F.FISH_TYPE) AS A0
JOIN (SELECT N.FISH_NAME AS FISH_NAME, MAX(F.LENGTH) AS LENGTH
      FROM FISH_INFO AS F
      JOIN FISH_NAME_INFO AS N
      ON N.FISH_TYPE = F.FISH_TYPE
      GROUP BY N.FISH_NAME) AS A1
ON A0.LENGTH = A1.LENGTH AND A0.FISH_NAME = A1.FISH_NAME
ORDER BY ID;